# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W_IV_Show.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 781, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.cBox_L1 = QtWidgets.QCheckBox(Form)
        self.cBox_L1.setGeometry(QtCore.QRect(140, 10, 92, 23))
        self.cBox_L1.setChecked(True)
        self.cBox_L1.setObjectName("cBox_L1")
        self.cBox_L2 = QtWidgets.QCheckBox(Form)
        self.cBox_L2.setGeometry(QtCore.QRect(140, 30, 92, 23))
        self.cBox_L2.setChecked(True)
        self.cBox_L2.setObjectName("cBox_L2")
        self.cBox_L3 = QtWidgets.QCheckBox(Form)
        self.cBox_L3.setGeometry(QtCore.QRect(260, 10, 92, 23))
        self.cBox_L3.setChecked(True)
        self.cBox_L3.setObjectName("cBox_L3")
        self.cBox_L4 = QtWidgets.QCheckBox(Form)
        self.cBox_L4.setGeometry(QtCore.QRect(260, 30, 92, 23))
        self.cBox_L4.setChecked(True)
        self.cBox_L4.setObjectName("cBox_L4")
        self.cBox_L5 = QtWidgets.QCheckBox(Form)
        self.cBox_L5.setGeometry(QtCore.QRect(380, 10, 92, 23))
        self.cBox_L5.setChecked(True)
        self.cBox_L5.setObjectName("cBox_L5")
        self.cBox_L6 = QtWidgets.QCheckBox(Form)
        self.cBox_L6.setGeometry(QtCore.QRect(380, 30, 92, 23))
        self.cBox_L6.setChecked(True)
        self.cBox_L6.setObjectName("cBox_L6")
        self.Btn_Back = QtWidgets.QPushButton(Form)
        self.Btn_Back.setGeometry(QtCore.QRect(700, 10, 90, 50))
        self.Btn_Back.setObjectName("Btn_Back")
        self.btnLoad = QtWidgets.QPushButton(Form)
        self.btnLoad.setGeometry(QtCore.QRect(10, 10, 90, 50))
        self.btnLoad.setObjectName("btnLoad")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cBox_L1.setText(_translate("Form", "L1"))
        self.cBox_L2.setText(_translate("Form", "L2"))
        self.cBox_L3.setText(_translate("Form", "L3"))
        self.cBox_L4.setText(_translate("Form", "L4"))
        self.cBox_L5.setText(_translate("Form", "L5"))
        self.cBox_L6.setText(_translate("Form", "L6"))
        self.Btn_Back.setText(_translate("Form", "Back"))
        self.btnLoad.setText(_translate("Form", "Load"))
