# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W_IV_Show.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 480)
        self.cBox_L6 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L6.setGeometry(QtCore.QRect(450, 40, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L6.setFont(font)
        self.cBox_L6.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L6.setChecked(True)
        self.cBox_L6.setObjectName("cBox_L6")
        self.cBox_L5 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L5.setGeometry(QtCore.QRect(450, 5, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L5.setFont(font)
        self.cBox_L5.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L5.setChecked(True)
        self.cBox_L5.setObjectName("cBox_L5")
        self.cBox_L3 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L3.setGeometry(QtCore.QRect(330, 5, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L3.setFont(font)
        self.cBox_L3.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L3.setChecked(True)
        self.cBox_L3.setObjectName("cBox_L3")
        self.cBox_L4 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L4.setGeometry(QtCore.QRect(330, 40, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L4.setFont(font)
        self.cBox_L4.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L4.setChecked(True)
        self.cBox_L4.setObjectName("cBox_L4")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 781, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.Btn_Back = QtWidgets.QPushButton(Dialog)
        self.Btn_Back.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.Btn_Back.setObjectName("Btn_Back")
        self.cBox_L1 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L1.setGeometry(QtCore.QRect(210, 5, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L1.setFont(font)
        self.cBox_L1.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L1.setChecked(True)
        self.cBox_L1.setObjectName("cBox_L1")
        self.cBox_L2 = QtWidgets.QCheckBox(Dialog)
        self.cBox_L2.setGeometry(QtCore.QRect(210, 40, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cBox_L2.setFont(font)
        self.cBox_L2.setIconSize(QtCore.QSize(16, 16))
        self.cBox_L2.setChecked(True)
        self.cBox_L2.setObjectName("cBox_L2")
        self.Btn_Load = QtWidgets.QPushButton(Dialog)
        self.Btn_Load.setGeometry(QtCore.QRect(10, 10, 70, 50))
        self.Btn_Load.setObjectName("Btn_Load")
        self.BtnAllShow = QtWidgets.QPushButton(Dialog)
        self.BtnAllShow.setGeometry(QtCore.QRect(90, 10, 50, 50))
        self.BtnAllShow.setObjectName("BtnAllShow")
        self.BtnAllHide = QtWidgets.QPushButton(Dialog)
        self.BtnAllHide.setGeometry(QtCore.QRect(150, 10, 50, 50))
        self.BtnAllHide.setObjectName("BtnAllHide")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cBox_L6.setText(_translate("Dialog", "L6"))
        self.cBox_L5.setText(_translate("Dialog", "L5"))
        self.cBox_L3.setText(_translate("Dialog", "L3"))
        self.cBox_L4.setText(_translate("Dialog", "L4"))
        self.Btn_Back.setText(_translate("Dialog", "Back"))
        self.cBox_L1.setText(_translate("Dialog", "L1"))
        self.cBox_L2.setText(_translate("Dialog", "L2"))
        self.Btn_Load.setText(_translate("Dialog", "Load"))
        self.BtnAllShow.setText(_translate("Dialog", "All\n"
"Show"))
        self.BtnAllHide.setText(_translate("Dialog", "All\n"
"Hide"))
