# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W_ica2308.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ica2308(object):
    def setupUi(self, ica2308):
        ica2308.setObjectName("ica2308")
        ica2308.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(ica2308)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnStop = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStop.setGeometry(QtCore.QRect(660, 160, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(40)
        self.BtnStop.setFont(font)
        self.BtnStop.setToolTip("")
        self.BtnStop.setObjectName("BtnStop")
        self.label_T4 = QtWidgets.QLabel(self.centralwidget)
        self.label_T4.setGeometry(QtCore.QRect(10, 60, 341, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_T4.setFont(font)
        self.label_T4.setObjectName("label_T4")
        self.TBrowser_msg = QtWidgets.QTextBrowser(self.centralwidget)
        self.TBrowser_msg.setGeometry(QtCore.QRect(10, 250, 781, 191))
        self.TBrowser_msg.setStyleSheet("QTextBrowser QScrollBar:vertical {\n"
"    width: 40px;              /* scrollbar width */\n"
"}")
        self.TBrowser_msg.setObjectName("TBrowser_msg")
        self.label_T3 = QtWidgets.QLabel(self.centralwidget)
        self.label_T3.setGeometry(QtCore.QRect(10, 100, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_T3.setFont(font)
        self.label_T3.setObjectName("label_T3")
        self.label_IN_Data = QtWidgets.QLabel(self.centralwidget)
        self.label_IN_Data.setGeometry(QtCore.QRect(404, 190, 251, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_IN_Data.setFont(font)
        self.label_IN_Data.setObjectName("label_IN_Data")
        self.label_Name = QtWidgets.QLabel(self.centralwidget)
        self.label_Name.setGeometry(QtCore.QRect(10, 10, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")
        self.BtnReRun = QtWidgets.QPushButton(self.centralwidget)
        self.BtnReRun.setGeometry(QtCore.QRect(590, 10, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(40)
        self.BtnReRun.setFont(font)
        self.BtnReRun.setToolTip("")
        self.BtnReRun.setObjectName("BtnReRun")
        ica2308.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ica2308)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        ica2308.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ica2308)
        self.statusbar.setObjectName("statusbar")
        ica2308.setStatusBar(self.statusbar)
        self.actionPush_Data = QtWidgets.QAction(ica2308)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        self.actionPush_Data.setFont(font)
        self.actionPush_Data.setObjectName("actionPush_Data")
        self.actionShow_Voltage = QtWidgets.QAction(ica2308)
        self.actionShow_Voltage.setObjectName("actionShow_Voltage")
        self.actionAbout = QtWidgets.QAction(ica2308)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRe_Initial = QtWidgets.QAction(ica2308)
        self.actionRe_Initial.setObjectName("actionRe_Initial")

        self.retranslateUi(ica2308)
        QtCore.QMetaObject.connectSlotsByName(ica2308)

    def retranslateUi(self, ica2308):
        _translate = QtCore.QCoreApplication.translate
        ica2308.setWindowTitle(_translate("ica2308", "ica2308"))
        self.BtnStop.setText(_translate("ica2308", "Stop"))
        self.label_T4.setText(_translate("ica2308", "UID: 00.00.00.00"))
        self.label_T3.setText(_translate("ica2308", "VCC: 0.00V"))
        self.label_IN_Data.setText(_translate("ica2308", "IN: 00.00V,0.000A"))
        self.label_Name.setText(_translate("ica2308", "label_Name"))
        self.BtnReRun.setText(_translate("ica2308", "ReRun"))
        self.actionPush_Data.setText(_translate("ica2308", "Push Data"))
        self.actionShow_Voltage.setText(_translate("ica2308", "Show Voltage"))
        self.actionAbout.setText(_translate("ica2308", "About"))
        self.actionRe_Initial.setText(_translate("ica2308", "Re-Initial"))
